name: sheeps_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+32

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # lcalizations package
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  equatable: ^2.0.5    #
  flutter_svg: ^2.0.7  #
  http: ^1.1.0   #prev 0.12.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5 #
  rxdart: ^0.27.7   #
  intl: ^0.18.0 #DateTime Parsing
  badges: ^3.1.1 #알림에 사용할 Badge
  flutter_datetime_picker_plus: ^2.0.1 #날짜 받아오기 위함
  get: ^4.6.5 #getX

  firebase_messaging: ^14.6.5 #firebase
  firebase_auth: ^4.7.2 #
  firebase_core: ^2.15.0
  firebase_dynamic_links: ^5.3.4 #동적링크

  path: ^1.8.3  #임시 디렉토리 가져옴
  sqflite: ^2.3.0 #로컬 db
  path_provider: ^2.0.15  #getDocumentDirectory... 가져옴
  page_transition: ^2.0.9 #페이지 넘어갈때 action
  flutter_local_notifications: ^9.7.0 #폰 켜져있을 때 알림
  vibration: ^1.8.1 #진동
  image_picker: ^1.0.2 #카메라 라이브러리가져오는
  flutter_reorderable_grid_view: ^4.0.0 #사진 애니메이션
  extended_image: ^8.0.2 #서버에있는 이미지 받아옴
  fluttertoast: ^8.2.2 #toast ui
  flutter_keyboard_visibility: ^5.4.1 #키보드 보이는 용
  webview_flutter: ^4.2.2 #웹뷰
  shared_preferences: ^2.2.0 #local 간단 db
  permission_handler: ^10.4.3 #권한 가져오기
  dio: ^5.3.2 #form data 전송
  custom_refresh_indicator: ^2.2.1 #scroll 상단 애니메이션
  image_gallery_saver: ^2.0.3
  transparent_image: ^2.0.1
  dotted_border: ^2.0.0+3 #테두리 점선
  flutter_slidable: ^3.0.0 #알림페이지 리스트 스와이프
  drag_and_drop_lists: ^0.3.3 #커뮤니티 카테고리 스와이프
  flutter_app_badger: ^1.5.0 #백그라운드 뱃지 카운트
  url_launcher: ^6.1.12 #외부 브라우저 연결
  iamport_flutter: ^0.10.10 #본인인증
  #flutter_link_previewer: ^2.5.2 #link previwer

  kakao_flutter_sdk: ^1.5.0 #카카오 sdk
  json_annotation: ^4.0.1 #카카오 sdk 사용하려면
  platform: ^3.0.0 #카카오 sdk 사용하려면
  package_info_plus: ^4.1.0 #카카오 sdk 관련
  share: ^2.0.4 #공유하기

  socket_io_client: ^1.0.0 #소켓
  sign_in_with_apple: ^3.0.0 #애플 로그인
  app_tracking_transparency: ^2.0.4 #아이폰 앱 추적관련
  google_sign_in: ^5.0.2 #구글 로그인
de_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/images/Badge/
    - assets/images/Badge/PersonalBadge/
    - assets/images/Badge/TeamBadge/
    - assets/images/Chat/
    - assets/images/Community/
    - assets/images/Coupon/
    - assets/images/DashBoard/
    - assets/images/Event/
    - assets/images/Global/
    - assets/images/LoginReg/
    - assets/images/NavigationBar/
    - assets/images/Profile/
    - assets/images/ProfileModify/
    - assets/images/Public/
    - assets/images/TotalNotification/
    - assets/images/Recruit/
    - assets/txt/bannerFile.txt
    - assets/raw/certificate.pem
    - assets/raw/rootCA.pem
    - assets/raw/server.crt
    - assets/raw/server.key
    - assets/raw/config.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
          weight: 700

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
